apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  labels:
    {{- include "ctron-drogue.labels" (dict "root" . "name" "keycloak-db-secret" "component" "sso") | nindent 4 }}

data:

  database: {{ .Values.postgresql.auth.database | b64enc | quote }}
  host: {{ printf "postgres.%s.svc.cluster.local" .Release.Namespace | b64enc | quote }}
  port: {{ .Values.postgresql.port | default "5432" | b64enc | quote }}
  username: {{ .Values.postgresql.auth.username | b64enc | quote }}
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
