{{- $ref := dict "root" . "name" "sso" "component" "sso" -}}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: keycloak
  annotations:
    {{- include "ctron-drogue.ingress.annotations" (dict "root" . "ingress" .Values.keycloak.ingress "termination" "reencrypt") | nindent 4 }}
  labels:
    {{- include "ctron-drogue.labels" $ref | nindent 4 }}
spec:
  {{- include "ctron-drogue.ingress.className" ( dict "root" . "ingress" .Values.keycloak.ingress) | nindent 2 }}
  rules:
    - host: {{ include "ctron-drogue.ingress.host" (dict "root" . "prefix" "sso" "ingress" .Values.keycloak.ingress ) }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8443
