{{- $ref := dict "root" . "name" "post-install-keycloak" "component" "sso" -}}
{{- if .Values.keycloak.postInstall.enabled -}}
kind: Job
apiVersion: batch/v1
metadata:
  name: post-install-keycloak
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    {{- include "ctron-drogue.labels" $ref | nindent 4 }}
spec:
  backoffLimit: 1000
  completions: 1
  parallelism: 1
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: post-install
          image: {{ .Values.keycloak.postInstall.image }}
          imagePullPolicy: IfNotPresent

          env:
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: credential-sso
                  key: ADMIN_USERNAME
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credential-sso
                  key: ADMIN_PASSWORD
            - name: KEYCLOAK_URL
              value: {{ include "ctron-drogue.ingress.url" (dict "root" . "prefix" "sso" "ingress" .Values.keycloak.ingress ) }}

          command:
            - bash
            - -exc
            - |
              # log in to keycloak
              /opt/jboss/keycloak/bin/kcadm.sh config credentials config --config /tmp/kcadm.config --server "$KEYCLOAK_URL/auth" --realm master --user "$ADMIN_USERNAME" --password "$ADMIN_PASSWORD"
{{- end -}}