kind: Service
apiVersion: v1
metadata:
  name: sso-tls
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: sso-tls
  labels:
    {{- include "ctron-drogue.labels" (dict "root" . "name" "sso-tls" "component" "sso") | nindent 4 }}
spec:
  ports:
    - port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: keycloak
  type: ClusterIP
