apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: admin
  labels:
    {{- include "ctron-drogue.labels" (dict "root" . "name" "admin" "component" "sso") | nindent 4 }}
spec:
  realmSelector:
    matchLabels:
      {{- include "ctron-drogue.selectorLabels" (dict "root" . "name" .Values.keycloak.realm "component" "sso") | nindent 6 }}
  user:
    username: "admin"
    firstName: "System"
    lastName: "Admin"
    email: {{ .Values.keycloak.adminEmail | default "user@example.com" }}
    emailVerified: false
    enabled: true
    credentials:
      - temporary: false
        type: password
        value: {{ .Values.keycloak.adminPassword }}
    realmRoles:
      - "offline_access"
    clientRoles:
      account:
        - "manage-account"
      realm-management:
        - "manage-users"
