kind: Secret
apiVersion: v1
metadata:
  name: timescaledb-secret
type: Opaque
data:
  read.username: {{ .Values.timescale.readUser | b64enc | quote }}
  read.password: {{ .Values.timescale.readPassword | b64enc | quote }}
  admin.username: {{ .Values.timescale.adminUser | b64enc | quote }}
  admin.password: {{ .Values.timescale.adminPassword | b64enc | quote }}
