{{- $ref := dict "root" . "name" "timescaledb" "component" "database" -}}
kind: Service
apiVersion: v1
metadata:
  name: timescaledb
  labels:
    {{ include "ctron-drogue.labels" $ref | nindent 4 }}
spec:
  selector:
    {{ include "ctron-drogue.selectorLabels" $ref | nindent 4 }}

  type: ClusterIP

  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: postgres
