{{- $ref := dict "root" . "name" "timescaledb" "component" "database" -}}
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: timescaledb
  labels:
    {{ include "ctron-drogue.labels" $ref | nindent 4 }}
spec:
  replicas: 1
  serviceName: timescaledb
  selector:
    matchLabels:
      {{ include "ctron-drogue.selectorLabels" $ref | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "ctron-drogue.labels" $ref | nindent 8 }}
    spec:
      containers:
        - name: timescaledb
          image: {{ .Values.timescale.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: {{ .Values.timescale.adminUser }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.timescale.adminPassword }}
            - name: POSTGRES_DB
              value: {{ .Values.timescale.name }}
            - name: PGDATA
              value: /var/lib/storage/pgdata
          volumeMounts:
            - mountPath: /var/lib/storage
              name: storage
              subPath: pgdata
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
