kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: timescaledb
  labels:
    app.kubernetes.io/name: timescaledb
    app.kubernetes.io/part-of: playground
spec:
  replicas: 1
  serviceName: timescaledb
  selector:
    matchLabels:
      app.kubernetes.io/name: timescaledb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: timescaledb
    spec:
      containers:
        - name: timescaledb
          image: {{ .Values.timescale.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: {{ .Values.timescale.adminUser }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.timescale.adminPassword }}
            - name: POSTGRES_DB
              value: {{ .Values.timescale.name }}
            - name: PGDATA
              value: /var/lib/storage/pgdata
          volumeMounts:
            - mountPath: /var/lib/storage
              name: storage
              subPath: pgdata
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
