global:
  cluster: openshift
  domain: -ctron-drogue.apps.wonderful.iot-playground.org

defaults:
  ingress: {}

timescale:
  image: docker.io/timescale/timescaledb-postgis:latest-pg12
  name: timescale

  adminUser: admin
  adminPassword: admin123456

  readUser: reader
  readPassword: reader123456

postgres:
  auth:
    postgresPassword: admin123456
    database: drogue
    username: drogue
    password: drogue1234

grafana:
  adminPassword: admin123456
  image: docker.io/grafana/grafana:9.2.6
  podSecurityContext:
    enabled: false
  ingress: {}

keycloak:
  realm: playground
  version: 20.0.1
  ingress: {}
  adminPassword: admin123456
  identityProviders: []
  postInstall:
    enabled: true
    image: quay.io/keycloak/keycloak:20.0.1
