{{- $ref := dict "root" . "name" "grafana" "component" "dashboard" -}}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: grafana
  annotations:
    {{- include "ctron-drogue.ingress.annotations" (dict "root" . "ingress" .Values.grafana.ingress ) | nindent 4 }}
  labels:
    {{- include "ctron-drogue.labels" $ref | nindent 4 }}
spec:
  {{- include "ctron-drogue.ingress.className" ( dict "root" . "ingress" .Values.keycloak.ingress) | nindent 2 }}
  rules:
    - host: {{ include "ctron-drogue.ingress.host" (dict "root" . "prefix" "grafana" "ingress" .Values.grafana.ingress ) }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  name: web
