kind: Service
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: playground
  name: grafana
spec:
  ports:
    - name: web
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: grafana
