apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: client-grafana
  labels:
    app.kubernetes.io/name: client-grafana
    app.kubernetes.io/part-of: playground
spec:
  realmSelector:
    matchLabels:
      {{- include "ctron-drogue.selectorLabels" (dict "root" . "name" .Values.keycloak.realm "component" "sso") | nindent 6 }}
  roles:
    - name: "grafana-admin"
    - name: "grafana-editor"
  client:
    clientId: grafana
    clientAuthenticatorType: client-secret
    enabled: true
    publicClient: false
    implicitFlowEnabled: false
    standardFlowEnabled: true
    fullScopeAllowed: false
    redirectUris:
      - {{ include "ctron-drogue.ingress.url" (dict "root" . "prefix" "grafana" "ingress" .Values.grafana.ingress ) }}/login/generic_oauth
